# Generated by Django 4.0.5 on 2022-07-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetablegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField()),
                ('timetablegroupname', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Timetable Group',
                'verbose_name_plural': 'Timetable Groups',
            },
        ),
        migrations.CreateModel(
            name='Timetablelessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teachers')),
                ('theclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupclasses')),
                ('timetablegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablegroup')),
            ],
            options={
                'verbose_name': 'Timetable Lesson',
                'verbose_name_plural': 'Timetable Lessons',
            },
        ),
        migrations.CreateModel(
            name='Timetablebreaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('theclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupclasses')),
                ('timetablegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablegroup')),
            ],
            options={
                'verbose_name': 'Timetable breaks',
                'verbose_name_plural': 'Timetable breaks',
            },
        ),
    ]
